### ISSUE TITLE
Consider a demo supporting Whip data specification

### ISSUE THREAD

**Issue by MattBlissett** [gbif/gbif-data-validator#74]
@peterdesmet presented Whip, a language to specify constraints on tabular data: https://github.com/inbo/whip

```
eventDate:
  dateformat: ['%Y-%m-%d', '%Y-%m', '%Y'] # Needs to be ISO8601 format, but don't allow ranges
  mindate: 1830-01-01                     # No dates before 1830
  empty: True                             # Empty values are allowed
```

It's something that could be implemented in the data validator, and GBIF more generally, to give tighter constraints for issues. We'd pick up typoed dates, countries etc.

Someone else mentioned SHACL, which is the W3C more complicated idea of the same https://www.w3.org/TR/shacl/

**Comment by timrobertson100** [comment]
It is a very interesting idea @MattBlissett 

I've been giving this some thought since Peter shared it:
1. We should explore if there is not an open standard somewhere already, instead of a home grown one. If not we might considering taking this to the broader community dealing with tabular data (e.g. RDA etc) as I think a _simple_ solution like this has great utility.
2. For a Java implementation we could consider compiling whip into some kind of assertions (e.g. code generated hamcrest).
3. We could allow whip specs to be registered against datasets so the infrastructure applied the assertions - specs could be reused across datasets.

**Comment by danstoner** [comment]
Take the example of "sex" noted in the syntax doc (
https://github.com/inbo/whip/blob/master/docs/syntax.md):

sex:
  allowed: [male, female, 'male, female'] # Use quotes to escape commas and
                            # white space. Will accept "male", "female" or
                            # "male, female", but not "male,female" (no
                            # white space) or "female, male".



The fact that all possible combinations of acceptable values would need to
be explicitly specified (including whitepsace !!!) seems like an extreme
limitation.


The spec already includes a concept of "empty".  Possibly other modifiers
would be useful such as "multiple values" or such.  Then the computers
could deal in lists and sets instead of making the specifier write all the
permutations.

Thus, for the sex case, it would look something like...

sex:
  allowed: [male, female]

**Comment by danstoner** [comment]
(sorry, sent before finished)


sex:
  allowed: [male, female]
  multiple_values_allowed: True



- Dan Stoner

**Comment by stijnvanhoey** [comment]
That usecase is (probably) covered by the whip syntax using the [`delimitedvalues` scope](https://github.com/inbo/whip/blob/master/docs/syntax.md#delimitedvalues),  cfr. the example from the description:

```
sex:
  delimitedvalues:
    delimiter: ' | '        # Required. Will use this to separate content 
                            # of a field. All specifications within the 
                            # "delimitedvalues" group apply to values 
                            # delimited with this delimiter.
    
    allowed: [male, female] # Will accept "male" or "female".
                            # Valid values for the whole field thus are: 
                            # "male", "female", "male | female", and 
                            # "female | male", but not "male, female" (wrong 
                            # delimiter), "male|female" (missing spaces), or 
                            # "male | " (empty second value).
```
assuming ` | ` as delimiter, but this supports the usage of  `,` as delimiter as well
